### ISSUE TITLE
cannot build under cygwin (win11)

### ISSUE THREAD

**Issue by benjaminbartsch** [arminbiere/gimsatul#3]
```
$ ./configure && make test
configure: gcc -Wall -O3 -DNDEBUG
configure: generated 'makefile'
gcc -Wall -O3 -DNDEBUG -c allocate.c
gcc -Wall -O3 -DNDEBUG -c analyze.c
gcc -Wall -O3 -DNDEBUG -c assign.c
gcc -Wall -O3 -DNDEBUG -c average.c
gcc -Wall -O3 -DNDEBUG -c backtrack.c
gcc -Wall -O3 -DNDEBUG -c barrier.c
./mkconfig.sh > config.h
gcc -Wall -O3 -DNDEBUG -c build.c
build.c: In function ‘print_banner’:
build.c:15:51: error: expected ‘:’ before numeric constant
   15 |   printf ("c Version %s%s\n", VERSION, GITID ? " " GITID : "");
      |                                                   ^
      |                                                   :
make: *** [makefile:9: build.o] Error 1
```

I am doing somehthing wrong?

**Comment by benjaminbartsch** [comment]
... okay I solved it by inserting a "+".

**Comment by a1880** [comment]
GITID is supposed to be string defined in config.h

It should be concatenated without extra '+'.

**Comment by benjaminbartsch** [comment]
...maybe it is an issue of the cygin-gcc? I am not good at C/C++, since I am a JAVA programmer.

**Comment by sfiruch** [comment]
Courtesy of @a1880, here's a win64 build of Gimsatul:
[gimsatul-ak-win64.zip](https://github.com/arminbiere/gimsatul/files/9455918/gimsatul-ak-win64.zip)

**Comment by benjaminbartsch** [comment]
Thank you so much, I will test it immediately!

**Comment by benjaminbartsch** [comment]
It is working perfectly in my JAVA-Project. Thank you!
(With "CygWin + gcc" I had errors with pipes beeing closed while sending the formula to the solver.)
