### ISSUE TITLE
How to get total number of all solutions?

### ISSUE THREAD

**Issue by liyu0x** [arminbiere/gimsatul#5]
Hi, How to get total number of all solutions?
only number, don't need the details.

Thank you.

**Comment by a1880** [comment]
As far as I know, _gimsatul_ does not support model counting (#SAT).
You may find [this survey](https://www.uni-ulm.de/fileadmin/website_uni_ulm/iui.inst.170/publications/2020-VaMoS-Sundermann.pdf) helpful to find #SAT solvers.

**Comment by liyu0x** [comment]
Ok， thank you

**Comment by arminbiere** [comment]
There is also model counting competition since a couple of years:
[https://mccompetition.org/2023/mc_description](https://mccompetition.org/2023/mc_description)

**Comment by liyu0x** [comment]
> 

ok, Thank you. Sir.
