### ISSUE TITLE
Bug in mkconfig.sh with confusion between int/string

### ISSUE THREAD

**Issue by GregoryMorse** [arminbiere/gimsatul#6]
```
#define GITID 0
```

should be:

```
#define GITID "0"
```

or compilation will fail when for example just extracting the ZIP and not having git involved.

**Comment by arminbiere** [comment]
Thanks, it is not a bug in `mkconfig.sh` but where we use `GITID` in `build.c`.  I have fixed it there in the development with commit (84f2bbe9) and eventually this will reach the master branch.
